### ISSUE TITLE
Email diff author instead of commit author in case build fails

### ISSUE THREAD

**Issue by ChaitanyaPramod** [uber/phabricator-jenkins-plugin#103]
Currently, whenever the build fails, an email is sent to the author of the last commit on which diff was applied, instead of the diff author. It'd be useful to email diff author who is more likely to understand what went wrong.

One example of where this happens is when the diff doesn't apply cleanly.

Update:

I forgot to mention that the emails are sent from **Jenkins Mailer Plugin** when *Send separate e-mails to individuals who broke the build* is enabled.

**Comment by sectioneight** [comment]
I'm not sure this is something that's fixable by the plugin, since the Jenkins mailer is reading your git history, and if you're applying the patch then jenkins *thinks* the commit being tested is actually master.

A failure applying the patch should be causing a harbormaster failure, and optionally you can have Jenkins post a comment with failures.
