### ISSUE TITLE
Add support for other code-coverage tools

### ISSUE THREAD

**Issue by melissa-playfab** [uber/phabricator-jenkins-plugin#142]
Hi,

I want to implement my own CoverageProvider to calculate coverage for the tools we use in-house (VSTest coverage and/or dotCover). However, what I'm missing is a way to select which coverage tool to use, perhaps in the Jenkins config. Is there an easy way to register this? Do you have plans to add maybe a dropdown or something like that in the config? I'm not very familiar with Jenkins plugin config, though the rest of your plugin seems straightforward and easy enough to add additional coverage providers to.

**Comment by sectioneight** [comment]
Is your current code coverage a jenkins plugin? Or it just outputs a file into your workspace that you'd like **this** plugin to parse?

**Comment by melissa-playfab** [comment]
It is a Jenkins plugin, but all the plugin does is dump a file into the workspace. We currently have that file picked up by EMMA and displayed as a part of the build, but that's pretty weak.

I don't have an issue writing the a specific CoverageProvider implementation that can pick up the file and parse it. What I don't know is how to select which CoverageProvider to use since there would then be two options. Does that make sense?

**Comment by sectioneight** [comment]
What is EMMA? How much of this is open source / closed standards? What does your coverage format look like?

Philosophically, I think this plugin should only include parsing support for open source (or open standard) formats (for testing and for coverage). Otherwise, we have code that we have to maintain that we don't have a reference implementation for, and is only useful for a single organization.

Would it be possible to convert your custom code coverage format into something Cobertura compatible? That's what we do at Uber -- for example, we use Golang's native cover tool, then use `gocov-xml` to turn that into Cobertura. For Python, we have pytest output cobertura coverage reports, etc.

If there's an additional **standard format** (e.g. there is a current request for JaCoCo) then I think we can put that on the roadmap, but I'm still not super clear on what features you are needing.

Alternatively, if you decide to go down the road of forking this plugin and building a closed-source parser there, I can provide some guidance. Just let me know.

Cheers,
Aiden

**Comment by melissa-playfab** [comment]
Ah, I don't mean to imply that I've written my own code coverage tool. Rather, we are using standard .net coverage tools which are neither one open sourced but are industry standards (and also happen to be poorly supported when it comes to other tools reading their formats):

https://www.jetbrains.com/dotcover/features/
https://msdn.microsoft.com/en-us/library/dd537628.aspx

I'm currently converting the output from Visual Studio 2013's code coverage tool into EMMA's format (http://emma.sourceforge.net/) which is, as I understand it, a very common Java coverage tool that is well-supported by Jenkins plugins. I wouldn't really mind if this plugin parsed EMMA instead of the .net formats, though the number of times we're converting formats is a bit onerous.

**Comment by sectioneight** [comment]
Thanks for the clarification, this makes more sense now. I'll leave it up to you whether it would be better to implement EMMA parsing or dotcover. As for the implementation, there are a couple options:

1- autodetect based on "build actions". This is how we used to do Cobertura. If there's already a Jenkins plugin that is parsing the coverage report, you can actually mark that plugin as an optional dependency of this one, then check if it's installed, then check to see if the current build has a coverage report. Then you might not have to add **any** parsing code here.

2- If there is no Jenkins plugin doing so already, it may make more sense to add a configuration option into this plugin to select your coverage format (and leave the default as "cobertura"). I can walk you through how to do that.

**Comment by melissa-playfab** [comment]
Option 1) seems like a good idea. The test results are being published by https://wiki.jenkins-ci.org/display/JENKINS/VsTestRunner+Plugin, so the reports go into a predictable location. That seems reasonable and something I can handle within scope.

**Comment by kornrunner** [comment]
Our codebase is mostly in PHP, and we're using PHPUnit for testing. It produces code coverage reports in Clover format and I haven't managed to find something that would convert Clover to Cobertura (so that we could use it along with this plugin and https://github.com/uber/uberalls). Would you consider implementing that format? It's open source, can be found at https://bitbucket.org/atlassian/clover

Thanks!

**Comment by frvade** [comment]
Hello, @kornrunner. We've recently ran in the same issue. Did you find any way to send phpunit coverage reports (in clover format) from jenkins to phabricator?

**Comment by kornrunner** [comment]
Unfortunately, no. Still awaiting for this to get implemented.

**Comment by frvade** [comment]
Anyway, thanks for lightning fast response.
