### ISSUE TITLE
Release 1.9.8 to Jenkins plugin repo?

### ISSUE THREAD

**Issue by ebabchick** [uber/phabricator-jenkins-plugin#189]
Hi, 

Version 1.9.8 from August never seemed to make it to the phabricator plugin page on Jenkins: https://wiki.jenkins-ci.org/display/JENKINS/Phabricator+Differential+Plugin

We'd love to get our paws on the "Abort existing builds when a new build referencing same diff is scheduled" feature -- let us know when it's updated on the Jenkins Update Center! Thanks

**Comment by sectioneight** [comment]
@jjx?

**Comment by jjx** [comment]
We tried to release a new version a while back, but ran in to an issue where Jenkins required us to have a parent pom of 2.6. Actually updating to 2.6 broke tests for us, so we held back from doing a release since then. If you'd like to consume the new version immediately, what you can do is simply (1) clone this repo (2) make package (3) Deploy the hpi generated from previous step to Jenkins from https://YOUR_CI_SERVER/pluginManager/advanced

**Comment by ChaitanyaPramod** [comment]
Hi, can we try releasing the plugin now?

**Comment by uSpike** [comment]
@kageiit This issue is closed but I do not see `1.9.8` on https://plugins.jenkins.io/phabricator-plugin - the latest is `1.9.7`.

**Comment by ChaitanyaPramod** [comment]
`1.9.8` has not been released yet.

I'm accidentally responsible for closing this issue. The unfortunate use of words in #246 to fix the blocker made Github think that this issue is resolved.

**Comment by ChaitanyaPramod** [comment]
@kageiit @jjx Thoughts on cutting a release for the plugin now that blockers have been cleared? It's been some time since the last one. 

PS: Can we reopen this issue until we make a release?

**Comment by kageiit** [comment]
I am doing some refactors to coverage providers to make them more performant. Plan to cut a release after that. Re-opening issue

**Comment by kageiit** [comment]
2.0.0 is now released
https://repo.jenkins-ci.org/releases/org/jenkins-ci/plugins/phabricator-plugin/2.0.0/
