### ISSUE TITLE
Compatibility with Diffusion

### ISSUE THREAD

**Issue by paulbriton** [uber/phabricator-jenkins-plugin#196]
Hi, I'm trying to configure this plugin in my current settings but I'm having some trouble.
Is this plugin compatible with adding comment in diffusion as well as in differential ? I've followed the installation steps and it's the only thing that doesn't work.

**Comment by sectioneight** [comment]
Great question. It's not documented but last I checked it works.

Basically this plugin is actually two plugins: a "pre-build" (apply the differential) and a "post-build" (post the results to harbormaster). The first part isn't useful for diffusion commits, but you can create a herald rule to trigger harbormaster builds for diffusion commits the same way you would for differentials, except instead of passing the DIFF_ID you'd pass the commit SHA and configure your job to build that SHA. A few of the features won't work (e.g. commenting currently uses the "differential.createcomment" command which won't work) but you can at least get build status and build artifacts (e.g. links to jenkins). I don't recall whether the inline coverage stuff works, not sure if that's interesting to you.

I'll leave this issue open so we document how this is used.

**Comment by paulbriton** [comment]
> you can create a herald rule to trigger harbormaster builds for diffusion commits the same way you would for differentials

That's exactly what I've done. 

> A few of the features won't work (e.g. commenting currently uses the "differential.createcomment" command which won't work) but you can at least get build status and build artifacts (e.g. links to jenkins).

I'm looking for a way to comment on a diffusion revision and add inline comments. As I understand, it won't work as is for diffusion ? Is it possible to use a "diffusion.createcomment" command ?
I get the build status from jenkins to phabricator with harbomaster. I was looking for a way to add more informations. So the plugin works well for diffusion, but I was interesting for more features.

Thank's for your answer.

**Comment by sectioneight** [comment]
Yea, we could definitely add a call to diffusion createcomment. That would
likely be a PR from the community as it's not a feature we use internally.
Should be pretty straightforward to add, assuming somebody wants to write
some Java :)

**Comment by sectioneight** [comment]
Although we'd probably want to rename the plugin at that point, since it's
currently called the "Phabricator Differential Plugin" since we didn't used
to support this :)

**Comment by paulbriton** [comment]
Ok I'll try to make a PR later this week, thank's for feedback.

**Comment by toelke** [comment]
Is there any progress on this?

**Comment by toelke** [comment]
I now see that the conduit-API does not allow adding inline-comments to diffusion-commits. Which would be the most useful feature...

So I guess there can't be any progress on this :-(

**Comment by paulbriton** [comment]
Sorry no progress. I still use Phabricator and Jenkins, but they stand alongside. 

I'm closing this for now.
