### ISSUE TITLE
Missing HarborMaster status in Diff

### ISSUE THREAD

**Issue by jaybbb** [uber/phabricator-jenkins-plugin#80]
Hello,

I have successfully setup phabricator-jenkins-plugin but I have an issue and I don't really know where to look (if it's harbormaster or the plugin).

So when a jenkins build start or end I only have comments in my diff details like this : 

![screenshot 2015-08-19 10 52 03](https://cloud.githubusercontent.com/assets/1963030/9352293/7340c5b2-4660-11e5-8ae0-254812216bcc.png)

I would like to get status update from harbormaster with a status like this : 
<img width="1026" alt="uberalls-integration" src="https://cloud.githubusercontent.com/assets/1963030/9352309/97d1ed7a-4660-11e5-91ad-41646222c850.png">

How can I do that ?

Thanks a lot for your plugin and your help !

Best Regards,

**Comment by sectioneight** [comment]
Unfortunately that behavior is controlled by Phabricator. Some time in the last few months, they removed the "completed building" message from the timeline. If you'd like to open up a ticket with upstream Phabricator to re-add it (or make it an option) they may be receptive. However, since Harbormaster just came out of prototype (during which they don't take bug reports / feature requests), things have been in flux recently.
